### ISSUE TITLE
G6 配置 modes 无法生效

### ISSUE THREAD

**Issue by Alecyrus** [ChrisShen93/VGEditor#17]
Vue: 最新版
Chrome：83

```html
  <v-g-editor>
          <Mind
            :graph="articleMindMapConfig"
            :onNodeClick="handleNodeClick"
            :data="articleMindMapData"
            :shortcut="{ zoomIn: true, zoomOut: true, drag:true }"
          />
        </v-g-editor>
```

```javascript
articleMindMapConfig = {
        container: '',
        width: 600,
        height: 500,
        modes: {
          default: ['drag-canvas', 'zoom-canvas']
        },
      },
```

**Comment by Alecyrus** [comment]
不能添加 modes，添加了就会导致无法推拽

**Comment by ChrisShen93** [comment]
> 不能添加 modes，添加了就会导致无法推拽

麻烦提供一个可复现的repo？

**Comment by Alecyrus** [comment]
配置里添加 modes这一项，就会发现 drag，click 都无法使用，而且我想实现通过鼠标滚轮去zoom，但是好像无法实现。
```javascript
{
        container: '',
        width: 600,
        height: 500,
        modes: {
          default: ['drag-canvas', 'zoom-canvas']
        },
      }
```

**Comment by Alecyrus** [comment]
好像无法应用 g6 的一些配置参数，比如 modes

**Comment by Alecyrus** [comment]
请问 RegisterCommand 中的 命令配置 如何设置？

**Comment by ChrisShen93** [comment]
> 请问 RegisterCommand 中的 命令配置 如何设置？

请参考文档：
https://chrisshen93.github.io/VGEditor/docs/api/registerCommand.html

**Comment by ChrisShen93** [comment]
由于个人时间问题，不能保证什么时候可以复现并处理上述的问题，在此表示抱歉。

为了不耽误您的宝贵时间，建议您参考其他同学的一些实现(比如 [X-Flowchart-Vue](https://github.com/OXOYO/X-Flowchart-Vue)，仅举一个例子，还有更多优秀的实现)。

对于VGEditor现存的问题，我会尽力尽早处理。同时原先的升级计划也会看个人时间进行相应的安排。

再次表示抱歉，并感谢使用VGEditor

**Comment by Alecyrus** [comment]
> https://chrisshen93.github.io/VGEditor/docs/api/registerCommand.html

文档只说了 命令配置是个 object，然就啥也没了。。

> 由于个人时间问题，不能保证什么时候可以复现并处理上述的问题，在此表示抱歉。
> 
> 为了不耽误您的宝贵时间，建议您参考其他同学的一些实现(比如 [X-Flowchart-Vue](https://github.com/OXOYO/X-Flowchart-Vue)，仅举一个例子，还有更多优秀的实现)。
> 
> 对于VGEditor现存的问题，我会尽力尽早处理。同时原先的升级计划也会看个人时间进行相应的安排。
> 
> 再次表示抱歉，并感谢使用VGEditor

没事，本来就是学习一下，不打算使用。我最终是用 D3.js 去做了。

**Comment by KevinBu** [comment]
请问如何让自定义的键盘事件生效比如delete的键盘事件
