### ISSUE TITLE
可不可以像GG-editor一样在codesandbox提供一些示例

### ISSUE THREAD

**Issue by zxgjwy0216** [ChrisShen93/VGEditor#7]
可不可以像GG-editor一样在codesandbox提供一些示例，比如我已经在mind中自定义了节点但是我该怎么去让data按这个节点的样式去渲染，我自定义了command，但是应该怎么在MindContexMenu中调用，大概的已经了解了，只是有些细节不知道怎么引入，感谢大佬

**Comment by ChrisShen93** [comment]
@zxgjwy0216 当前版本只是有些功能可用，个人对目前的项目不怎么满意，所以暂时不打算提供

下个版本会采用你的意见

感谢你的宝贵意见
